import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TanStackQueryProviders from "@/utils/TanStackQueryProviders";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanStackQueryProviders>
          <div className="min-h-screen bg-background">
            <Header />
            <main className="container mx-auto px-4 py-8">{children}</main>
          </div>
        </TanStackQueryProviders>
      </body>
    </html>
  );
}
